#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/common

cd $OPENSHIFT_REPO_DIR
java -jar converter*.jar |& /usr/bin/logshifter &

