#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=${JAVA_HOME}/bin:${PATH}

export SPRING_PROFILES_ACTIVE=openshift

cd $OPENSHIFT_REPO_DIR
#switch to ./gradlew bootRun?
java -jar build/libs/*.jar |& /usr/bin/logshifter &

